//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class helpdesk
    {
        public int ID { get; set; }
        public Nullable<int> SeverityID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Comments { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> RowCreatedDateTime { get; set; }
        public Nullable<System.DateTime> RowModifiedDateTime { get; set; }
        public Nullable<int> RowModifiedSYSUserID { get; set; }
        public Nullable<int> RowCreatedSYSUserID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Severity Severity { get; set; }
        public virtual Status Status { get; set; }
        public virtual SYSUser SYSUser { get; set; }
    }
}
